# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QPushButton, QSizePolicy, QSpinBox, QTextEdit,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(699, 298)
        self.pushBtn_run = QPushButton(Form)
        self.pushBtn_run.setObjectName(u"pushBtn_run")
        self.pushBtn_run.setGeometry(QRect(120, 180, 101, 31))
        font = QFont()
        font.setFamilies([u"Agency FB"])
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.pushBtn_run.setFont(font)
        self.label_episode_index = QLabel(Form)
        self.label_episode_index.setObjectName(u"label_episode_index")
        self.label_episode_index.setGeometry(QRect(240, 70, 201, 31))
        font1 = QFont()
        font1.setFamilies([u"Agency FB"])
        font1.setPointSize(20)
        self.label_episode_index.setFont(font1)
        self.spinBox_task = QSpinBox(Form)
        self.spinBox_task.setObjectName(u"spinBox_task")
        self.spinBox_task.setGeometry(QRect(60, 110, 141, 41))
        self.spinBox_task.setFont(font1)
        self.spinBox_episode = QSpinBox(Form)
        self.spinBox_episode.setObjectName(u"spinBox_episode")
        self.spinBox_episode.setGeometry(QRect(240, 110, 139, 41))
        self.spinBox_episode.setFont(font1)
        self.spinBox_episode.setMaximum(9999)
        self.label_task_index = QLabel(Form)
        self.label_task_index.setObjectName(u"label_task_index")
        self.label_task_index.setGeometry(QRect(60, 80, 151, 21))
        self.label_task_index.setFont(font1)
        self.pushBtn_index_set = QPushButton(Form)
        self.pushBtn_index_set.setObjectName(u"pushBtn_index_set")
        self.pushBtn_index_set.setGeometry(QRect(160, 240, 141, 31))
        font2 = QFont()
        font2.setFamilies([u"DejaVu Sans Mono"])
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setItalic(True)
        self.pushBtn_index_set.setFont(font2)
        self.pushBtn_stop = QPushButton(Form)
        self.pushBtn_stop.setObjectName(u"pushBtn_stop")
        self.pushBtn_stop.setGeometry(QRect(250, 180, 101, 31))
        font3 = QFont()
        font3.setFamilies([u"Agency FB"])
        font3.setPointSize(20)
        font3.setBold(True)
        self.pushBtn_stop.setFont(font3)
        self.label_task_name = QLabel(Form)
        self.label_task_name.setObjectName(u"label_task_name")
        self.label_task_name.setGeometry(QRect(10, 20, 101, 21))
        font4 = QFont()
        font4.setFamilies([u"Ubuntu"])
        font4.setPointSize(14)
        self.label_task_name.setFont(font4)
        self.pushBtn_task_save = QPushButton(Form)
        self.pushBtn_task_save.setObjectName(u"pushBtn_task_save")
        self.pushBtn_task_save.setGeometry(QRect(370, 240, 151, 41))
        self.pushBtn_task_save.setFont(font1)
        self.textEdit_task_name = QTextEdit(Form)
        self.textEdit_task_name.setObjectName(u"textEdit_task_name")
        self.textEdit_task_name.setGeometry(QRect(120, 20, 411, 31))
        font5 = QFont()
        font5.setPointSize(12)
        self.textEdit_task_name.setFont(font5)
        self.checkBox_parquet = QCheckBox(Form)
        self.checkBox_parquet.setObjectName(u"checkBox_parquet")
        self.checkBox_parquet.setGeometry(QRect(400, 210, 101, 21))
        font6 = QFont()
        font6.setFamilies([u"Arial"])
        font6.setPointSize(12)
        self.checkBox_parquet.setFont(font6)
        self.checkBox_parquet.setIconSize(QSize(14, 14))
        self.pushBtn_delete = QPushButton(Form)
        self.pushBtn_delete.setObjectName(u"pushBtn_delete")
        self.pushBtn_delete.setGeometry(QRect(420, 120, 91, 31))
        font7 = QFont()
        font7.setFamilies([u"DejaVu Sans"])
        font7.setPointSize(14)
        font7.setBold(True)
        self.pushBtn_delete.setFont(font7)
        self.pushBtn_delete.setStyleSheet(u"QPushButton {\n"
"    color: red;          /* \u6587\u5b57\u984f\u8272 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: gray;             /* disable(\u53cd\u7070) \u72c0\u614b\u6587\u5b57\u984f\u8272 */\n"
"}")
        self.spinBox_index = QSpinBox(Form)
        self.spinBox_index.setObjectName(u"spinBox_index")
        self.spinBox_index.setGeometry(QRect(50, 240, 81, 31))
        font8 = QFont()
        font8.setFamilies([u"DejaVu Sans"])
        font8.setPointSize(12)
        self.spinBox_index.setFont(font8)
        self.spinBox_index.setMaximum(9999)
        self.label_index = QLabel(Form)
        self.label_index.setObjectName(u"label_index")
        self.label_index.setGeometry(QRect(50, 220, 71, 21))
        font9 = QFont()
        font9.setFamilies([u"Ubuntu"])
        font9.setPointSize(12)
        self.label_index.setFont(font9)
        self.groupBox_video = QGroupBox(Form)
        self.groupBox_video.setObjectName(u"groupBox_video")
        self.groupBox_video.setGeometry(QRect(550, 20, 131, 261))
        font10 = QFont()
        font10.setPointSize(12)
        font10.setBold(True)
        font10.setItalic(False)
        font10.setStrikeOut(False)
        self.groupBox_video.setFont(font10)
        self.checkBox_show_video = QCheckBox(self.groupBox_video)
        self.checkBox_show_video.setObjectName(u"checkBox_show_video")
        self.checkBox_show_video.setGeometry(QRect(10, 30, 111, 21))
        font11 = QFont()
        font11.setFamilies([u"Arial"])
        font11.setPointSize(12)
        font11.setBold(True)
        font11.setItalic(False)
        font11.setStrikeOut(False)
        self.checkBox_show_video.setFont(font11)
        self.checkBox_show_video.setIconSize(QSize(14, 14))
        self.checkBox_show_video.setChecked(True)
        self.checkBox_save_head = QCheckBox(self.groupBox_video)
        self.checkBox_save_head.setObjectName(u"checkBox_save_head")
        self.checkBox_save_head.setGeometry(QRect(10, 60, 111, 21))
        self.checkBox_save_head.setFont(font11)
        self.checkBox_save_head.setLayoutDirection(Qt.LeftToRight)
        self.checkBox_save_head.setIconSize(QSize(14, 14))
        self.checkBox_save_head.setChecked(True)
        self.checkBox_save_left = QCheckBox(self.groupBox_video)
        self.checkBox_save_left.setObjectName(u"checkBox_save_left")
        self.checkBox_save_left.setGeometry(QRect(10, 90, 111, 21))
        self.checkBox_save_left.setFont(font11)
        self.checkBox_save_left.setLayoutDirection(Qt.LeftToRight)
        self.checkBox_save_left.setIconSize(QSize(14, 14))
        self.checkBox_save_left.setChecked(True)
        self.checkBox_save_right = QCheckBox(self.groupBox_video)
        self.checkBox_save_right.setObjectName(u"checkBox_save_right")
        self.checkBox_save_right.setGeometry(QRect(10, 120, 111, 21))
        self.checkBox_save_right.setFont(font11)
        self.checkBox_save_right.setLayoutDirection(Qt.LeftToRight)
        self.checkBox_save_right.setIconSize(QSize(14, 14))
        self.checkBox_save_right.setChecked(True)
        self.checkBox_save_side = QCheckBox(self.groupBox_video)
        self.checkBox_save_side.setObjectName(u"checkBox_save_side")
        self.checkBox_save_side.setGeometry(QRect(10, 150, 111, 21))
        self.checkBox_save_side.setFont(font11)
        self.checkBox_save_side.setLayoutDirection(Qt.LeftToRight)
        self.checkBox_save_side.setIconSize(QSize(14, 14))
        self.checkBox_save_side.setChecked(True)
        self.checkBox_save_sider = QCheckBox(self.groupBox_video)
        self.checkBox_save_sider.setObjectName(u"checkBox_save_sider")
        self.checkBox_save_sider.setGeometry(QRect(10, 180, 111, 21))
        self.checkBox_save_sider.setFont(font11)
        self.checkBox_save_sider.setLayoutDirection(Qt.LeftToRight)
        self.checkBox_save_sider.setIconSize(QSize(14, 14))
        self.checkBox_save_sider.setChecked(True)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.pushBtn_run.setText(QCoreApplication.translate("Form", u"Run", None))
        self.label_episode_index.setText(QCoreApplication.translate("Form", u"Episode_Index", None))
        self.label_task_index.setText(QCoreApplication.translate("Form", u"Task_Index", None))
        self.pushBtn_index_set.setText(QCoreApplication.translate("Form", u"Index Set", None))
        self.pushBtn_stop.setText(QCoreApplication.translate("Form", u"Stop", None))
        self.label_task_name.setText(QCoreApplication.translate("Form", u"Task_Name", None))
        self.pushBtn_task_save.setText(QCoreApplication.translate("Form", u"Task_End", None))
        self.checkBox_parquet.setText(QCoreApplication.translate("Form", u"To Parquet", None))
        self.pushBtn_delete.setText(QCoreApplication.translate("Form", u"Delete", None))
        self.label_index.setText(QCoreApplication.translate("Form", u"Set Index", None))
        self.groupBox_video.setTitle(QCoreApplication.translate("Form", u"Video Setting", None))
        self.checkBox_show_video.setText(QCoreApplication.translate("Form", u"Show Video", None))
        self.checkBox_save_head.setText(QCoreApplication.translate("Form", u"Save Head", None))
        self.checkBox_save_left.setText(QCoreApplication.translate("Form", u"Save Left", None))
        self.checkBox_save_right.setText(QCoreApplication.translate("Form", u"Save Right", None))
        self.checkBox_save_side.setText(QCoreApplication.translate("Form", u"Save Side", None))
        self.checkBox_save_sider.setText(QCoreApplication.translate("Form", u"Save Sider", None))
    # retranslateUi

